### ISSUE TITLE
Roles not found

### ISSUE THREAD

**Issue by eymen-elkum** [cakemanager/cakephp-cakeadmin#2]
Hi
I have installed the plugin in my project, but I didnt found the role table.

**Comment by leoruhland** [comment]
Hi @ayman-alkom!
I think to use the roles you should install [Users](https://github.com/cakemanager/cakephp-users) plugin as referenced in [this blog post](http://cakemanager.org/new-cakeadmin-plugin-announced/).
But remember:

>  [Users](https://github.com/cakemanager/cakephp-users) is a non-stable plugin for CakePHP 3.x at this time. It is currently under development and should be considered experimental.

**Comment by bobmulder** [comment]
@ayman-alkom, The CakeAdmin plugin has another approach. This plugin has only administrator-users wich are the administrators of the backend. To have an usermanagement-system you need - as @leoruhland said - the Users-plugin.

Note that your application now is completely apart from the admin-panel. Thats the beauty of this plugin ;).

Please chat with us at [Gitter](https://gitter.im/cakemanager/cakephp-cakeadmin) for questions!

Greetz,

Bob

**Comment by eymen-elkum** [comment]
OK thanks a lot
I will use the gitter
